### ISSUE TITLE
Indian comma for any number printed

### ISSUE THREAD

**Issue by TejasAvinashShetty** [asprazz/covid19-cli#14]
**Thank you for brainstorming**
You are welcome. Thank you too, for making this.
**Is your feature request related to a problem? Please describe.**
It is always difficult to gauge how many lakh, crore people are affected.  Say  533088 
**Describe the solution you'd like**
Ensure Indian style commas. For example, write  533088  as  5,33,088 
**Describe alternatives you've considered**
If not possible  533,088 American style numbering would be bearable too.
**Additional context**

Not necessary

**Comment by asprazz** [comment]
Yeah that might be a very good idea, in turn in enhancing reading capability.
Thank You!
