### ISSUE TITLE
first digit is missing 

### ISSUE THREAD

**Issue by TejasAvinashShetty** [asprazz/covid19-cli#17]
**Describe the bug**
The first digit is missing in every number.

**To Reproduce**
1. covid19 India -s Maharastra

**Expected behavior**
![image](https://user-images.githubusercontent.com/27445854/79552068-274e4480-80b8-11ea-805e-58c44c3f17e7.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/27445854/79552132-3cc36e80-80b8-11ea-9033-a87e4c15a109.png)

**Desktop (please complete the following information):**
 - OS: [Linux (Ubuntu)]
 - Terminal bash

**Additional context**
It seems that fixing the Indian comma #14  issue caused this.

**Comment by asprazz** [comment]
@TejasAvinashShetty It is really a bad unexpected behaviour. I am glad that you noticed it.

I didn't test our new feature of using commas in between numbers and pushed it anyway, sorry for it! 

Would you like to fix it?


PS: I love mailspring too. ❤️

**Comment by asprazz** [comment]
https://github.com/asprazz/covid19-cli/tree/master/covid19/helpers.py

There is a function for formatting numbers 
There might be a fix or 


There might be a better approach for doing this...

You are all welcome.

**Comment by asprazz** [comment]
![image](https://user-images.githubusercontent.com/19568165/79570496-2a0c6200-80d7-11ea-8441-724dd409b758.png)

Hi @TejasAvinashShetty, will you please verify again ? Because I am getting the desired output
