### ISSUE TITLE
number formatting doesn't work , locale setting unsupported

### ISSUE THREAD

**Issue by KulkarniSuraj** [asprazz/covid19-cli#19]
**Describe the bug**
whenever tried to run the program I get an error saying
locale setting unsupported . Maybe related to number formatting on windows

**To Reproduce**
Steps to reproduce the behaviour:
1. change working directory to covid19-cli
2. run `python covid19/__main__.py india`

**Expected behaviour**
should display the data properly

**Screenshots**

![locale bug](https://user-images.githubusercontent.com/30728951/79643296-f8bb9100-81bf-11ea-9d7e-bbe99a3aebf8.JPG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Terminal : git bash

**Additional context**
I think the problem is with `locale.setlocale()` on windows

**Comment by asprazz** [comment]
Thank you @KulkarniSuraj  for reporting it
This is because I never tested #15

**Comment by asprazz** [comment]
fixed by aa34b8c
