### ISSUE TITLE
World status fetcher (same as country's) but with all the countries 

### ISSUE THREAD

**Issue by asprazz** [asprazz/covid19-cli#9]
**Thank you for brainstorming**
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by asprazz** [comment]
@KulkarniSuraj I was wondering for apis for tracking world cases
I found this one also used by other CLI applications 
`https://corona.lmao.ninja/all` what do you think can we use this for global tracking?

**Comment by asprazz** [comment]
https://corona.lmao.ninja/all

**Comment by KulkarniSuraj** [comment]
> @KulkarniSuraj I was wondering for apis for tracking world cases
> I found this one also used by other CLI applications
> `https://corona.lmao.ninja/all` what do you think can we use this for global tracking?

seems good to me. we can try it out until we find something else

**Comment by asprazz** [comment]
Cool :smiley:
